slogan: "Coding the future"

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  # - title: About
  #   url: about
  #   intro: "About me."
  #   icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/rookie9209
    intro: "My Github account."
    icon: "fa fa-github"

widgets:
- search
- category
# - tagcloud
# - recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname: gnaix

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: true
  siteid: